on:
  push:
    branches:
      - main

jobs:
  code-block:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo  >> "$GITHUB_STEP_SUMMARY" '```json'
          jq -n >> "$GITHUB_STEP_SUMMARY" '{ one: "two", three: 4 }'
          echo  >> "$GITHUB_STEP_SUMMARY" '```'

  emoji:
    runs-on: ubuntu-latest
    needs: [code-block]
    steps:
      - run: |
          echo >> "$GITHUB_STEP_SUMMARY" ':tada:'
